import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Emanuel Hiebeler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-background h-screen">
        <div className="flex justify-center">
          <div className="w-[60vw] h-screen flex flex-col justify-center text-3xl">
            <div>
              <span className="text-primary">&lt;Name&gt;</span>
              <span className=""> Emanuel Hiebeler </span>
              <span className="text-primary">&lt;/Name&gt;</span>
            </div>
            <div>
              <span className="text-primary">&lt;Age&gt;</span>
              <span className=""> 17 Jahre </span>
              <span className="text-primary">&lt;/Age&gt;</span>
            </div>
            <div className="flex flex-col">
              <span className="text-primary">&lt;Social Media&gt;</span>
              <div className="flex flex-col ml-10">
                <div>
                  <span className="text-primary">&lt;Insta&gt;</span>
                  <span className="">@hiebeler05</span>
                  <span className="text-primary">&lt;/Insta&gt;</span>
                </div>
                <div>
                  <span className="text-primary">&lt;Github&gt;</span>
                  <span className="">HIEBELER</span>
                  <span className="text-primary">&lt;/Github&gt;</span>
                </div>
              </div>
              <span className="text-primary">&lt;/Social Media&gt;</span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
